name: Deploy
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  full_pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Project
        run: make

      - name: Running tests
        run: |
          chmod +x scripts/test.sh
          ./scripts/test.sh

      - name: Building .deb package
        run: |
          chmod +x scripts/package.sh
          ./scripts/package.sh

      - name: Uploading Artifact
        uses: actions/upload-artifact@v4
        with:
          name: deb-package
          path: reverse-words.deb

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/reverse-words:1.0 .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/reverse-words:1.0
