name: Deploy
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  full_pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Checkout repository
        uses: actions/checkout@v3

      - name: 2. Build Project (Рисунок 2)
        run: make

      - name: 3. Running tests (Рисунок 7)
        run: |
          chmod +x scripts/test.sh
          ./scripts/test.sh

      - name: 4. Building .deb package (Рисунок 6)
        run: |
          chmod +x scripts/package.sh
          ./scripts/package.sh

      - name: 5. Uploading Artifact
        uses: actions/upload-artifact@v4
        with:
          name: deb-package
          path: reverse-words.deb

      - name: 6. Login to DockerHub (Рисунок 5)
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: 7. Build and Push Docker Image (Рисунки 4-5)
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/reverse-words:1.0 .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/reverse-words:1.0
